config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :title,
  presence: { message: "入力してください"},
  length: {minimum: 3, message: "短すぎ！"}

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  mount_uploader :picture, PictureUploader
  validates :title,
  presence: { message: "入力してください"}
  validate  :picture_size

  scope :unfinished, ->{ where(done: false)}

  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

    def project_params
      params[:project].permit(:title)
    end

    def set_project
      @project = Project.find(params[:id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])#:idはrake routesコマンドで見れば渡されていることがわかる
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end

  private

    def task_params
      params[:task].permit(:title, :picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag "TaskApp-logo.png" %><!-- 画像の埋め込み -->

    <%= yield %>

    <%= link_to "Home", projects_path %><!-- リンクの埋め込み -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>


<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
  <% end %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>EditNew</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
  <li>
    <%= link_to project.title, project_path(project.id) %>
    (<%= project.tasks.unfinished.count %>)(<%= project.tasks.count %>)
    <%= link_to "[Edit]", edit_project_path(project.id) %>
    <%= link_to "[Delte]", project_path(project.id), method: :delete, data: {confirm: "are you sure?"} %>

  </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<div class="border-head">
  <ul>
    <% @project.tasks.each do |task| %>
      <li class="border-line">
        <%= check_box_tag '','',task.done, {'data-id' => task.id, 'data-project_id' => task.project_id} %>
        <%= task.title %>
        <%= link_to "[Delete]", project_task_path(task.project_id, task.id), method: :delete, data: {confirm: "are you sure?"} %>
        <p><%= image_tag task.picture.url if task.picture? %></p>
      </li>

    <% end %>

    <li class="input-form">
      <%= form_for [@project, @project.tasks.build] do |f| %>
      <%= f.text_field :title %>
      <%= f.submit %>
      <p><%= f.file_field :picture %></p>
      <% end %>
    </li>
  </ul>
</div>

<script>
$(function(){
  $("input[type=checkbox]").click(function() {
      $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
  });
});
</script>